name: Bump version

# Only fire on the "release" branch
on:
  push:
    branches:
      - release

jobs:

  # Bump version, generate changelog, and create tags
  tag:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Generate changelog and tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npx standard-version
      - name: Push changelog and tag
        uses: ad-m/github-push-action@master
        with:
          branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
